### ISSUE TITLE
Getting error when access camera

### ISSUE THREAD

**Issue by AdamFM** [atyenoria/react-native-webrtc-janus-gateway#7]
`FATAL EXCEPTION: main
Process: com.classmiles.student, PID: 26949
                                                                        java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference
                                                                            at com.oney.WebRTCModule.GetUserMediaImpl.getUserVideo(GetUserMediaImpl.java:395)
                                                                            at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:293)
                                                                            at com.oney.WebRTCModule.GetUserMediaImpl.access$000(GetUserMediaImpl.java:29)
                                                                            at com.oney.WebRTCModule.GetUserMediaImpl$1.invoke(GetUserMediaImpl.java:257)
                                                                            at com.oney.WebRTCModule.GetUserMediaImpl$3.invoke(GetUserMediaImpl.java:458)
                                                                            at com.oney.WebRTCModule.PermissionUtils$2.onReceiveResult(PermissionUtils.java:189)
                                                                            at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)`

**Comment by atyenoria** [comment]
@AdamFM 
Thanks for reporting. Could you clarify the following points ?
1. Device name and Android version. emulator?
2. Whether all devices or emulators happens or not

**Comment by AdamFM** [comment]
1. mi4i, android version 5.0.2 Lolilop
i use webrtc not from u have.. so i edit same with u have and its work

**Comment by atyenoria** [comment]
Okay, then will close.
